pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages{
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1'){
                        sh """
                          cd security_group
                          terraform init -reconfigure
                        """
                    }
                }
            }
        }
         stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1'){
                        sh """
                          cd security_group
                          terraform plan 
                        """
                    }
                }
            }
        }
         stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1'){
                        sh """
                          cd security_group
                          terraform apply -auto-approve
                        """
                    }
                }
            }
        }
    }
}