pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages{
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1'){
                        sh """
                          cd security_group
                          terraform init -reconfigure
                        """
                    }
                }
            }
        }
         stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1'){
                        sh """
                          cd security_group
                          terraform plan 
                        """
                    }
                }
            }
        }
         stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1'){
                        sh """
                          cd security_group
                          terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('bastion eks acm'){
            parallel {
              stage('trigger bastion'){
                steps{
                    script {
                       build job: 'bastion',
                       propagate: false,
                       wait: false
                    }

                 }
              }
               stage('trigger eks'){
                 steps{
                    script {
                       build job: 'eks',
                       propagate: false,
                       wait: false
                    }

                 }
              }
              stage('ACM alb') {
                 stages {
                    stage('ACM') {
                        steps {
                            script {
                              build job: 'ACM',
                              propagate: false,
                              wait: false
                            }
                        }
                    }
                    stage('alb') {
                        steps {
                            script {
                              build job: 'alb',
                              propagate: false,
                              wait: false
                            }
                        }
                    }
                 }
              }
               
            }

        }
    }
}