pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm') 
    }
    stages {
        stage('init'){
            steps {
                script {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1') {

                      sh """
                        cd ACM
                        terraform init -reconfigure
                      """
                    }
                }
            }
        }
         stage('plan'){
            steps {
                script {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1') {
                      sh """
                        cd ACM
                        terraform plan
                      """
                    }
                    
                }
            }
        }
         stage('apply'){
            // input {
            //     message "should we continue"
            //     ok "Yes, we should"
            //     submitter "alice,bob"
            // }
            steps {
                script {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1'){

                    
                      sh """
                        cd ACM
                        terraform apply -auto-approve
                      """
                    }
                }
            }
        }
       
    }
}