pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm') 
    }
    stages {
        stage('init'){
            steps {
                script {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1') {

                      sh """
                        cd vpc
                        terraform init -reconfigure
                      """
                    }
                }
            }
        }
         stage('plan'){
            steps {
                script {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1') {
                      sh """
                        cd vpc
                        terraform plan
                      """
                    }
                    
                }
            }
        }
         stage('apply'){
            // input {
            //     message "should we continue"
            //     ok "Yes, we should"
            //     submitter "alice,bob"
            // }
            steps {
                script {
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1'){

                    
                      sh """
                        cd vpc
                        terraform apply -auto-approve
                      """
                    }
                }
            }
        }
        stage('Trigger sg') {
            steps {
                script {
                    build job: 'sg'
                    propagate: false,  // even SG fails VPC will not be effected
                    wait: false // VPC will not wait for SG pipeline completion
                }
            }
        }
    }
}